### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_augment'

### ISSUE THREAD

**Issue by Liumomo30** [xiongGPR/MGPR-GAN#1]
我在调用的时候出现ModuleNotFoundError: No module named 'diff_augment'，但我不知道如何安装他，请问应该使用哪条命令如何安装呢？感谢回答

**Comment by xiongGPR** [comment]
不需要这个文件。你可以删掉有关的代码。




K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiongGPR/MGPR-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月23日(星期六) 晚上8:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiongGPR/MGPR-GAN] ModuleNotFoundError: No module named 'diff_augment' (Issue #1)





 
我在调用的时候出现ModuleNotFoundError: No module named 'diff_augment'，但我不知道如何安装他，请问应该使用哪条命令如何安装呢？感谢回答
